create or replace TYPE "ARR_WS_CAMPUS" AS TABLE OF varchar2(20 byte);
/

create or replace TYPE "ARR_WS_ES_TIPO_DOC" AS TABLE OF CHAR(4 BYTE);
/
  create or replace TYPE "ARR_WS_NU_DOC" AS TABLE OF CHAR(10 BYTE);
/
create or replace TYPE "ARR_WS_AP_PATERNO" AS TABLE OF VARCHAR2(70 BYTE);
/
create or replace TYPE "ARR_WS_AP_MATERNO" AS TABLE OF VARCHAR2(70 BYTE); 
/
create or replace TYPE "ARR_WS_NO_TRABAJADOR" AS TABLE OF VARCHAR2(50 BYTE); 
/
create or replace TYPE "ARR_WS_NO_FACULTAD" AS TABLE OF VARCHAR2(100 BYTE);
/
create or replace TYPE "ARR_WS_NO_EAP" AS TABLE OF VARCHAR2(100 BYTE); 
/
create or replace TYPE "ARR_WS_DE_CARGA" AS TABLE OF CHAR(8 BYTE) ; 
/
create or replace TYPE "ARR_WS_NO_CURSO" AS TABLE OF VARCHAR2(200 BYTE); 
/
create or replace TYPE "ARR_WS_NU_GRUPO" AS TABLE OF CHAR(2 BYTE);
/
create or replace TYPE "ARR_WS_DE_HORARIO" AS TABLE OF CHAR(112 BYTE) ; 
/
create or replace TYPE "ARR_WS_CA_HLAB" AS TABLE OF NUMBER(5,2) ; 
/
create or replace TYPE "ARR_WS_DE_CONDICION" AS TABLE OF CHAR(30 BYTE);
/
create or replace TYPE "ARR_WS_DE_TIPO_CURSO" AS TABLE OF CHAR(30 BYTE);
/



create or replace procedure rhsp_ws_carga_academica(
ARR_ES_TIPO_DOC  in ARR_WS_ES_TIPO_DOC,
ARR_NU_DOC in ARR_WS_NU_DOC,
ARR_AP_PATERNO in  ARR_WS_AP_PATERNO,
ARR_AP_MATERNO in ARR_WS_AP_MATERNO,
ARR_NO_TRABAJADOR in ARR_WS_NO_TRABAJADOR,
ARR_NO_FACULTAD in ARR_WS_NO_FACULTAD,
ARR_NO_EAP in ARR_WS_NO_EAP,
ARR_DE_CARGA in ARR_WS_DE_CARGA,
ARR_NO_CURSO in ARR_WS_NO_CURSO,
ARR_NU_GRUPO in ARR_WS_NU_GRUPO,
ARR_DE_HORARIO in ARR_WS_DE_HORARIO,
ARR_CA_HLAB in ARR_WS_CA_HLAB,
ARR_DE_CONDICION in ARR_WS_DE_CONDICION,
ARR_DE_TIPO_CURSO in ARR_WS_DE_TIPO_CURSO
) 
as
begin
   FOR i IN 1 .. ARR_NO_TRABAJADOR.COUNT
   LOOP
     update rhtm_carga_academica set es_carga_academica ='0';
   END LOOP;

end;
/
