SELECT a."ID_CONTRATO",
    a."ID_DGP",
    a.fe_desde,
    a.fe_hasta,
    a.fe_cese,
    a."ID_FUNC",
    a."LI_CONDICION",
    a."CA_SUELDO",
    a."CA_REINTEGRO",
    a."CA_ASIG_FAMILIAR",
    a."HO_SEMANA",
    a."NU_HORAS_LAB",
    a."DIA_CONTRATO",
    a."TI_TRABAJADOR",
    a."LI_REGIMEN_LABORAL",
    a."ES_DISCAPACIDAD",
    a."TI_CONTRATO",
    a."LI_REGIMEN_PENSIONARIO",
    a."ES_CONTRATO_TRABAJADOR",
    a."US_CREACION",
    a.fe_creacion ,
    a."US_MODIF",
    a.fe_modif,
    a."US_IP",
    a.fe_vacacio_ini,
    a.fe_vacacio_fin,
    a."ES_CONTRATO",
    a."ID_FILIAL",
    a."ID_PUESTO",
    a."CA_BONO_ALIMENTO",
    a."LI_TIPO_CONVENIO",
    a."ES_FIRMO_CONTRATO",
    a."NU_CONTRATO",
    a."DE_OBSERVACION",
    a."ES_APOYO",
    a."TI_HORA_PAGO",
    a."NU_DOCUMENTO",
    
    a."ES_ENTREGAR_DOC_REGLAMENTOS",
    a."ES_REGISTRO_HUELLA",
    a."DE_REGISTRO_SISTEM_REMU",
    a."ID_TRABAJADOR",
    a."CA_SUELDO_TOTAL",
    a."ID_REGIMEN_LABORAL",
    a."ID_SUB_MODALIDAD",
    a."ID_GRUPO_OCUPACION",
    a.fe_suscripcion,
    a."CO_TI_MONEDA",
    a."CO_TI_REM_VARIAB",
    a."DE_REMU_ESPECIE",
    a."DE_RUC_EMP_TRAB",
    a."CO_SUCURSAL",
    a."DE_MYPE",
    a."ES_TI_CONTRATACION",
    a."CA_BEV",
    a.no_puesto,
    a.no_seccion,
    a.no_area,
    a.no_dep,
    a.no_direccion,
    g.DE_GRUPO_OCUPACION,
    a.DE_SUB_MODALIDAD,
    a.DE_MODALIDAD,
    a.NO_TRABAJADOR,
    a.AP_PATERNO,
    a.AP_MATERNO,
    a.LI_DI_DOM_A_D1,
    a.DI_DOM_A_D2 ,
    a.LI_DI_DOM_A_D3,
    a.DI_DOM_A_D4,
    a.LI_DI_DOM_A_D5,
    a.DI_DOM_A_D6,
    a.NO_PROVINCIA,
    a.NO_DISTRITO,
    a.fe_sus,
    a.fe_des,
    a.fe_has,
    a.ID_PLANTILLA_CONTRACTUAL,
    a.CA_BONIFICACION_P,
    a.ES_SECRE_IS,
    a.LI_RELIGION,
    a.PRACTICANTE
FROM(
SELECT c."ID_CONTRATO",
    c."ID_DGP",
    TO_CHAR(c."FE_DESDE",'dd/mm/yyyy') AS fe_desde,
    TO_CHAR(c."FE_HASTA",'dd/mm/yyyy') AS fe_hasta,
    TO_CHAR(c."FE_CESE",'dd/mm/yyyy')  AS fe_cese,
    c."ID_FUNC",
    c."LI_CONDICION",
    c."CA_SUELDO",
    c."CA_REINTEGRO",
    c."CA_ASIG_FAMILIAR",
    c."HO_SEMANA",
    c."NU_HORAS_LAB",
    c."DIA_CONTRATO",
    c."TI_TRABAJADOR",
    c."LI_REGIMEN_LABORAL",
    c."ES_DISCAPACIDAD",
    c."TI_CONTRATO",
    c."LI_REGIMEN_PENSIONARIO",
    c."ES_CONTRATO_TRABAJADOR",
    c."US_CREACION",
    TO_CHAR(c."FE_CREACION",'dd/mm/yyyy') AS fe_creacion,
    c."US_MODIF",
    TO_CHAR(c."FE_MODIF",'dd/mm/yyyy') AS fe_modif,
    c."US_IP",
    TO_CHAR(c."FE_VACACIO_INI",'dd/mm/yyyy') AS fe_vacacio_ini,
    TO_CHAR(c."FE_VACACIO_FIN",'dd/mm/yyyy') AS fe_vacacio_fin,
    c."ES_CONTRATO",
    c."ID_FILIAL",
    c."ID_PUESTO",
    c."CA_BONO_ALIMENTO",
    c."LI_TIPO_CONVENIO",
    c."ES_FIRMO_CONTRATO",
    c."NU_CONTRATO",
    c."DE_OBSERVACION",
    c."ES_APOYO",
    c."TI_HORA_PAGO",
    (tr."NU_DOC") AS "NU_DOCUMENTO",
 
    c."ES_ENTREGAR_DOC_REGLAMENTOS",
    c."ES_REGISTRO_HUELLA",
    c."DE_REGISTRO_SISTEM_REMU",
    c."ID_TRABAJADOR",
    c."CA_SUELDO_TOTAL",
    c."ID_REGIMEN_LABORAL",
    c."ID_SUB_MODALIDAD",
    c."ID_GRUPO_OCUPACION",
    TO_CHAR(c."FE_SUSCRIPCION",'dd/mm/yyyy') AS fe_suscripcion,
    c."CO_TI_MONEDA",
    c."CO_TI_REM_VARIAB",
    c."DE_REMU_ESPECIE",
    c."DE_RUC_EMP_TRAB",
    c."CO_SUCURSAL",
    c."DE_MYPE",
    c."ES_TI_CONTRATACION",
    c."CA_BEV",
    pd.no_puesto,
    pd.no_seccion,
    pd.no_area,
    pd.no_dep,
    pd.no_direccion,
    s.DE_SUB_MODALIDAD,
    m.DE_MODALIDAD,
    tr.NO_TRABAJADOR,
    tr.AP_PATERNO,
    tr.AP_MATERNO,
    tr.LI_DI_DOM_A_D1,
    tr.DI_DOM_A_D2 ,
    tr.LI_DI_DOM_A_D3,
    tr.DI_DOM_A_D4,
    tr.LI_DI_DOM_A_D5,
    tr.DI_DOM_A_D6,
    tr.LI_RELIGION,
    pr.NO_PROVINCIA,
    ds.NO_DISTRITO,
    TO_CHAR(c."FE_SUSCRIPCION",'dd/month/yyyy','nls_date_language=spanish') AS fe_sus,
    TO_CHAR(c."FE_DESDE",'dd/month/yyyy','nls_date_language=spanish')       AS fe_des,
    TO_CHAR(c."FE_HASTA",'dd/month/yyyy','nls_date_language=spanish')       AS fe_has,
    c.ID_PLANTILLA_CONTRACTUAL,
    c.CA_BONIFICACION_P,
    c.ES_SECRE_IS,
    c.PRACTICANTE 
  FROM rhtm_contrato c,
    RHVD_puesto_direccion pd,
    RHTX_MODALIDAD m ,
    RHTX_SUB_MODALIDAD s,
    RHTM_TRABAJADOR tr,
    RHTX_UB_PROVINCIA pr,
    RHTX_UB_DISTRITO ds
  WHERE c.id_puesto           = pd.id_puesto
  AND c.ID_TRABAJADOR         =tr.ID_TRABAJADOR
  AND tr.ID_DISTRITO          =ds.ID_DISTRITO
  AND ds.ID_PROVINCIA         =pr.ID_PROVINCIA
  AND s.ID_SUB_MODALIDAD      = c.ID_SUB_MODALIDAD
  AND s.ID_MODALIDAD          = m.ID_MODALIDAD
  AND c.ES_CONTRATO_TRABAJADOR='1') a LEFT OUTER JOIN RHTX_GRUPO_OCUPACION g ON(g.ID_GRUPO_OCUPACION  = a.ID_GRUPO_OCUPACION)