server.servlet.context-path=/gth
#jsp
spring.mvc.view.prefix= /WEB-INF/jsp/views/
spring.mvc.view.suffix= .jsp

security.basic.enabled=false
server.port = 8080

management.server.port=8082
management.endpoints.web.exposure.include=health,info
management.endpoint.shutdown.enabled=false
management.endpoint.health.show-details=never

info.app.name=Talento Humano
info.app.description=First Version
info.app.version=0.0.1

spring.output.ansi.enabled=ALWAYS

#Config Server
spring.application.name=gth
spring.config.import=configserver:
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.username=${CONFIG_SERVER_USER:admin}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}