spring:
  application:
    name: recruitment-service
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5434/recruitment_db}
    username: ${DB_USERNAME:recruitment_user}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5434/recruitment_db}
    user: ${DB_USERNAME:recruitment_user}
    password: ${DB_PASSWORD}
    schemas: public

server:
  port: 8082
  address: ${SERVER_ADDRESS:127.0.0.1}

app:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.r2dbc.core: DEBUG
