ALTER TABLE contract ADD COLUMN direction_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN department_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN area_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN section_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN branch_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN food_bonus NUMERIC(14,2);
ALTER TABLE contract ADD COLUMN bev_bonus NUMERIC(14,2);
ALTER TABLE contract ADD COLUMN position_bonus NUMERIC(14,2);
ALTER TABLE contract ADD COLUMN total_salary NUMERIC(14,2);
ALTER TABLE contract ADD COLUMN payment_hour_type VARCHAR(64);
ALTER TABLE contract ADD COLUMN is_disability BOOLEAN;
ALTER TABLE contract ADD COLUMN is_boss BOOLEAN;
ALTER TABLE contract ADD COLUMN agreement_type VARCHAR(64);
ALTER TABLE contract ADD COLUMN signing_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE contract ADD COLUMN vacation_start_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE contract ADD COLUMN vacation_end_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE contract ADD COLUMN currency_type VARCHAR(8);
ALTER TABLE contract ADD COLUMN variable_remuneration VARCHAR(64);
ALTER TABLE contract ADD COLUMN occupation_group_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN sub_modality_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN is_intern BOOLEAN;
ALTER TABLE contract ADD COLUMN documents_delivered BOOLEAN;
ALTER TABLE contract ADD COLUMN fingerprint_registered BOOLEAN;
ALTER TABLE contract ADD COLUMN payroll_registered BOOLEAN;
ALTER TABLE contract ADD COLUMN company_ruc VARCHAR(20);
ALTER TABLE contract ADD COLUMN branch_code VARCHAR(32);
ALTER TABLE contract ADD COLUMN special_situation_id VARCHAR(64);
ALTER TABLE contract ADD COLUMN special_situation_desc TEXT;
