ALTER TABLE contract ALTER COLUMN requisition_id DROP NOT NULL;
ALTER TABLE contract ADD COLUMN IF NOT EXISTS parent_contract_id UUID REFERENCES contract(id) ON DELETE SET NULL;
ALTER TABLE contract ADD COLUMN IF NOT EXISTS is_special_case BOOLEAN DEFAULT FALSE;
