package com.app.dgp.controller;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Map;

public interface DGPRepository extends JpaRepository<DGP, String> {

    @Query(value = "SELECT f.de_pasos, "
            + "  f.nu_pasos, s.es_autorizacion as esAuthorization, rhfu_count_aut_dgp(:iddgp) as count_aut," +
            "rhfu_detalle_puesto_aut (:iddrp, f.id_pasos, :iddep) as puesto_aut "
            + "FROM "
            + "  (SELECT p.id_pasos, "
            + "    p.id_proceso, "
            + "    rp.id_detalle_req_proceso, "
            + "    p.de_pasos, "
            + "    p.nu_pasos, "
            + "    p.co_pasos, "
            + "    pro.no_proceso, "
            + "    rp.id_direccion, "
            + "    rp.id_departamento, "
            + "    rp.id_requerimiento "
            + "  FROM rhtc_pasos p , "
            + "    rhtv_proceso pro, "
            + "    rhtr_detalle_req_proceso rp "
            + "  WHERE pro.id_proceso = p.id_proceso "
            + "  AND rp.id_proceso    = pro.id_proceso "
            + "  AND rp.ES_REQ_PROCESO='1' "
            + "  AND p.ES_PASOS       ='1' "
            + "  ) f "
            + "LEFT OUTER JOIN "
            + "  (SELECT pu.NO_PUESTO, "
            + "    du.NO_USUARIO, "
            + "    a.co_pasos, "
            + "    a.DE_PASOS, "
            + "    a.es_autorizacion, "
            + "    a.fe_creacion, "
            + "    a.id_autorizacion, "
            + "    a.id_departamento, "
            + "    a.id_detalle_pasos, "
            + "    a.id_detalle_req_proceso, "
            + "    a.id_dgp, "
            + "    a.id_direccion, "
            + "    a.id_pasos, "
            + "    a.id_proceso, "
            + "    a.id_puesto, "
            + "    a.id_requerimiento, "
            + "    a.no_proceso, "
            + "    a.nu_pasos, "
            + "    a.us_creacion , "
            + "    dt.AP_PATERNO, "
            + "    dt.AP_MATERNO, "
            + "    dt.NO_TRABAJADOR, "
            + "    dgp.CA_SUELDO, "
            + "    du.AP_PATERNO    AS us_ap_p, "
            + "    du.AP_MATERNO    AS us_ap_mat , "
            + "    du.NO_TRABAJADOR AS us_no_tr, "
            + "    du.NO_PUESTO     AS us_no_puesto, "
            + "    du.NO_AREA       AS us_no_area, "
            + "    du.NO_DEP        AS us_no_dep "
            + "  FROM "
            + "    (SELECT a.id_detalle_req_proceso, "
            + "      a.id_dgp, "
            + "      a.id_pasos, "
            + "      d.id_proceso, "
            + "      d.id_detalle_pasos , "
            + "      d.DE_PASOS, "
            + "      d.NU_PASOS, "
            + "      d.CO_PASOS , "
            + "      d.no_proceso , "
            + "      d.id_puesto, "
            + "      d.id_direccion, "
            + "      d.id_departamento , "
            + "      d.id_requerimiento , "
            + "      a.id_autorizacion, "
            + "      a.fe_creacion, "
            + "      a.es_autorizacion, "
            + "      a.us_creacion "
            + "    FROM "
            + "      (SELECT * FROM rhvd_req_paso_pu "
            + "      ) d "
            + "    LEFT OUTER JOIN rhtv_autorizacion a "
            + "    ON ( a.id_pasos             =d.id_pasos "
            + "    AND d.id_pasos              =a.id_pasos "
            + "    AND d.id_puesto             =a.id_puesto "
            + "    AND d.id_detalle_req_proceso=a.id_detalle_req_proceso) "
            + "    ) a , "
            + "    rhtm_dgp dgp , "
            + "    rhtm_trabajador dt , "
            + "    rhvd_usuario du , "
            + "    rhvd_puesto_direccion pu "
            + "  WHERE dgp.id_dgp                 =a.id_dgp "
            + "  AND dt.id_trabajador             = dgp.id_trabajador "
            + "  AND du.id_usuario                =a.us_creacion "
            + "  AND dgp.id_puesto                =pu.id_puesto "
            + "  AND dgp.id_dgp                   = :iddgp "
            + "  ) s ON ( s.ID_DETALLE_REQ_PROCESO=f.ID_DETALLE_REQ_PROCESO "
            + "AND f.id_pasos                     =s.id_pasos ) "
            + "WHERE f.ID_DETALLE_REQ_PROCESO     = :iddrp "
            + "ORDER BY to_number(SUBSTR(f.nu_pasos,2,LENGTH(f.nu_pasos))) ASC" , nativeQuery = true)
    List<Map<String, String>> findDgpProcessDetails(@Param("iddgp") String iddgp, @Param("iddrp") String idrp, @Param("iddep") String iddep);
    
}
